# Generated by Django 5.2.11 on 2026-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre del Jugador')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido del Jugador')),
                ('number', models.CharField(max_length=100, verbose_name='Número de Camiseta')),
                ('position', models.CharField(choices=[('armador', 'Armador'), ('punta', 'Punta'), ('central', 'Central'), ('Opuesto', 'Opuesto'), ('libero', 'Libero'), ('universal', 'Universal / Sin posición')], default='universal', max_length=20, verbose_name='Posición')),
            ],
        ),
    ]
