# Generated by Django 5.2.11 on 2026-02-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Número de Camiseta'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('armador', 'Armador'), ('punta', 'Punta'), ('central', 'Central'), ('opuesto', 'Opuesto'), ('libero', 'Libero'), ('universal', 'Universal / Sin posición')], default='universal', max_length=20, verbose_name='Posición'),
        ),
    ]
